name: CI

on:
  push:
    branches: [main, master, dev_task_2]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: "cr.selcloud.ru/qwerty"
  IMAGE_NAME: "chat-server"
  CONTAINER_NAME: "chat-server-container"
  DB_CONTAINER_NAME: "chat-db-container"
  DB_IMAGE_NAME: "postgres:13"

jobs:
  # Go Job - выполняет билд, тесты и линтинг кода
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum

      - name: Build
        run: go build -o ./bin/ -v ./...

      - name: Test
        run: go test -v ./...

  linter:
    runs-on: ubuntu-latest
    needs: build-and-test  # Выполняется после build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=30m --config=./.golangci.pipeline.yaml

  # CI/CD Job - выполняет сборку и деплой Docker-образа
  image-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test, linter]  # Выполняется после Go-шагов
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file for CI
        run: |
          echo "PG_DATABASE_NAME=auth" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_PORT=5433" >> .env
          echo "MIGRATION_DIR=./migrations" >> .env
          echo "GRPC_HOST=0.0.0.0" >> .env
          echo "GRPC_PORT=50051" >> .env
          echo "PG_DSN=host=$DB_CONTAINER_NAME port=5433 dbname=auth user=${{secrets.PG_USER}} password=${{secrets.PG_PASSWORD}} sslmode=disable" >> .env
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile .

      - name: Build and Push Migrator Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build --no-cache --push --tag $REGISTRY/chat_migrator:$TAG_NAME -f migration.Dockerfile .

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push  # Выполняется после успешного image-build-and-push
    steps:
      - name: Deploy to Supernova server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 33
          envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, CONTAINER_NAME
          script: |
            # Создаем файл .env
            echo "PG_DATABASE_NAME=chat" >> .env
            echo "PG_USER=${{ secrets.PG_USER }}" >> .env
            echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
            echo "PG_PORT=5433" >> .env
            echo "MIGRATION_DIR=./migrations" >> .env

            # Создаем сеть
            docker network create chat-service-network || true

            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d -p 50051:50051 --network chat-service-network --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME

            echo "Проверяем наличие контейнера базы данных..."
            if [ "$(docker ps -q -f name=$DB_CONTAINER_NAME)" ]; then
              echo "Контейнер базы данных уже запущен"
            else
              echo "Создаем контейнер базы данных..."
              docker run -d --name $DB_CONTAINER_NAME \
              --network chat-service-network \
              -e POSTGRES_DB=chat \
              -e POSTGRES_USER=${{ secrets.PG_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }} \
              -v postgres_data:/var/lib/postgresql/chat_data \
              -p 50061:5433 $DB_IMAGE_NAME || echo "Ошибка при создании контейнера базы данных"
            fi

            # Запускаем мигратор
            docker stop chat_migrator || echo "Контейнер chat_migrator не запущен"
            docker rm chat_migrator || echo "Контейнер chat_migrator не существует"
            docker run --network chat-service-network --name chat_migrator \
            --env-file .env \
            -e DB_HOST=$DB_CONTAINER_NAME -t $REGISTRY/chat_migrator:$TAG_NAME || echo "Ошибка запуска контейнера миграций"
          